# title of website
title: LV

# description of website
description: arieslj's navigation site

# favicon of website
favicon: "https://github.com/arieslj.png?size=40"

# your website url
url: https://lv.xxx

# github profile url
github: https://github.com/arieslj/load

# footer message
footer: © 2021-2021 @arieslj

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu
      - biying

# Google analytics
google_analytics: G-EXE1PJ8CR2

content:
  categories:
    - name: 常用推荐
      sites:
        - name: GitHub
          description: GitHub
          url: https://github.com/
        - name: V2EX
          description: 技术论坛，创意工作者们的社区
          url: https://www.v2ex.com/
        - name: 斗鱼
          description: 直播平台
          url: https://www.douyu.com/
    - name: 网盘工具
      sites:
        - name: 天翼云解析
          description: 天翼云直链解析
          url: https://189.ly93.cc/
        - name: 天翼云下载
          description: 天翼云盘免登录下载
          url: https://api.ezini.vip/
        - name: ip.sb
          description: IP 获取
          url: https://ip.sb/
         - name: NbDown
          description: 度盘解析
          url: https://down.5nb.me/         
    - name: 论坛社区
      sites:
        - name: 虎扑步行街
          description: 虎扑步行街热门话题，每日话题
          url: https://bbs.hupu.com/all-gambia
        - name: V2EX
          description: 技术论坛，创意工作者们的社区
          url: https://www.v2ex.com/
        - name: GitHub Trending
          description: GitHub 排行榜
          url: https://github.com/trending  
        - name: Lobsters
          description: 技术论坛
          url: https://lobste.rs/
        - name: 热门微博
          description: 热门微博，微博热搜
          url: https://weibo.com/hot
        - name: AnyKnew
          description: 全网热点
          url: https://www.anyknew.com/#/
        - name: 后续
          description: 有记忆的新闻，持续追踪热点新闻
          url: https://houxu.app/
        - name: 知微事见
          description: 互联网社会热点聚合平台
          url: https://ef.zhiweidata.com/          
    - name: 公司网站
      sites:
        - name: 鹿由
          description: 尚德企业OA
          url: https://im.sunlands.com
        - name: EHR
          description: 尚德人力系统
          url: https://ehr.sunlands.com
        - name: 利维坦
          description: 傻逼系统
          url: https://bf.sunlands.com/opportunity
        - name: 大鱼
          description: 贼难用的系统
          url: https://bf.ministudy.com/exception
        - name: 鹰眼
          description: 傻逼到极点的系统
          url: http://172.16.116.70:35353/
    - name: 图床网站
      sites:
        - name: Imgur
          description: 老牌国外免费图床
          url: https://imgur.com/
        - name: sm.ms
          description: 国内免费图床
          url: https://sm.ms/
    - name: 休闲娱乐
      sites:
        - name: 小霸王
          description: 在线小霸王游戏机，支持联机
          url: https://www.yikm.net/
        - name: 扫雷
          description: 网页版扫雷，开箱即用
          url: http://www.cctvjs.net/mine/
        - name: 斗鱼
          description: 直播平台
          url: https://www.douyu.com/
    - name: 学习资源
      sites:
        - name: Leetcode
          description: 面试准备算法题必备，国内站和国外站数据互通
          url: https://leetcode-cn.com/
        - name: CodeTop
          description: 企业面试题库
          url: https://codetop.cc/#/home
        - name: 菜鸟教程
          description: 入门教程合集
          url: https://www.runoob.com/
    - name: 有意思的网站
      sites:
        - name: 秘密花园
          description: 1999 年建立的网站，远古网站
          url: http://www.yini.org/
